# Generated by Django 5.2.4 on 2025-08-01 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la maladie')),
                ('description', models.TextField(verbose_name='Description')),
                ('symptomes_typiques', models.TextField(verbose_name='Symptômes typiques')),
                ('gravite', models.CharField(choices=[('faible', 'Faible'), ('modérée', 'Modérée'), ('élevée', 'Élevée'), ('critique', 'Critique')], default='modérée', max_length=20, verbose_name='Gravité')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'animal")),
                ('numero_identification', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'identification")),
                ('type_animal', models.CharField(choices=[('bovin', 'Bovin'), ('ovin', 'Ovin'), ('caprin', 'Caprin'), ('porcin', 'Porcin'), ('équidé', 'Équidé')], max_length=20, verbose_name="Type d'animal")),
                ('race', models.CharField(max_length=100, verbose_name='Race')),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('poids', models.FloatField(blank=True, null=True, verbose_name='Poids (kg)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanificationSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_soin', models.CharField(choices=[('vaccination', 'Vaccination'), ('vermifuge', 'Vermifuge'), ('controle', 'Contrôle vétérinaire'), ('traitement', 'Traitement'), ('autre', 'Autre')], max_length=20, verbose_name='Type de soin')),
                ('nom_soin', models.CharField(max_length=200, verbose_name='Nom du soin')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_prevue', models.DateTimeField(verbose_name='Date prévue')),
                ('date_realisation', models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('reporte', 'Reporté'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('rappel_envoye', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins_planifies', to='livestock.animal')),
                ('veterinaire_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planification de soin',
                'verbose_name_plural': 'Planifications de soins',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='SymptomeObserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Température (°C)')),
                ('frequence_cardiaque', models.IntegerField(blank=True, null=True, verbose_name='Fréquence cardiaque (bpm)')),
                ('frequence_respiratoire', models.IntegerField(blank=True, null=True, verbose_name='Fréquence respiratoire')),
                ('niveau_activite', models.IntegerField(choices=[(1, 'Très faible'), (2, 'Faible'), (3, 'Normal'), (4, 'Élevé'), (5, 'Très élevé')], default=3, verbose_name="Niveau d'activité")),
                ('appetit', models.IntegerField(choices=[(1, 'Aucun appétit'), (2, 'Appétit faible'), (3, 'Appétit normal'), (4, 'Bon appétit'), (5, 'Appétit excessif')], default=3, verbose_name='Appétit')),
                ('fievre', models.BooleanField(default=False, verbose_name='Fièvre')),
                ('toux', models.BooleanField(default=False, verbose_name='Toux')),
                ('diarrhee', models.BooleanField(default=False, verbose_name='Diarrhée')),
                ('ecoulement_nasal', models.BooleanField(default=False, verbose_name='Écoulement nasal')),
                ('boiterie', models.BooleanField(default=False, verbose_name='Boiterie')),
                ('abattement', models.BooleanField(default=False, verbose_name='Abattement')),
                ('perte_poids', models.BooleanField(default=False, verbose_name='Perte de poids')),
                ('notes_veterinaire', models.TextField(blank=True, verbose_name='Notes vétérinaire')),
                ('date_observation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'observation")),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptomes_observes', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'Symptôme observé',
                'verbose_name_plural': 'Symptômes observés',
                'ordering': ['-date_observation'],
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du traitement')),
                ('description', models.TextField(verbose_name='Description du traitement')),
                ('dosage', models.CharField(max_length=200, verbose_name='Dosage recommandé')),
                ('duree_jours', models.IntegerField(verbose_name='Durée en jours')),
                ('contre_indications', models.TextField(blank=True, verbose_name='Contre-indications')),
                ('maladies', models.ManyToManyField(related_name='traitements', to='livestock.maladie', verbose_name='Maladies traitées')),
            ],
            options={
                'verbose_name': 'Traitement',
                'verbose_name_plural': 'Traitements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilite', models.FloatField(verbose_name='Probabilité de la prédiction')),
                ('confirme_par_veterinaire', models.BooleanField(default=False, verbose_name='Confirmé par vétérinaire')),
                ('notes_diagnostic', models.TextField(blank=True, verbose_name='Notes du diagnostic')),
                ('date_diagnostic', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='livestock.animal')),
                ('veterinaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maladie_predite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics_predits', to='livestock.maladie')),
                ('symptome_observe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.symptomeobserve')),
                ('traitement_recommande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.traitement')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
                'ordering': ['-date_diagnostic'],
            },
        ),
    ]
